#!/bin/bash
# inverse order of channels:
conda config --env --add channels conda-forge
conda config --env --add channels defaults
R -e "IRkernel::installspec()" --no-save >/dev/null

exec=R
kernel=ir

# works for <env>/bin/exec
execdir="$(dirname "$(type -p "$exec")")"
env="$(dirname "$execdir")"
wrap="$execdir/wrap/$exec"

create-wrappers -t conda -b "$execdir" -f "$exec" -d "$(dirname "$wrap")" --conda-env-dir "$env"

if [[ "$OSTYPE" == "msys" ]]; then
    pref="$(cygpath "$APPDATA")/jupyter"
    wrap="$(cygpath -w "$wrap").bat"
elif [[ "$OSTYPE" =~ ^darwin ]]; then
    pref="$HOME/Library/Jupyter"
else
    pref="$HOME/.local/share/jupyter"; fi
export wrap="$wrap"
export kernelpath="$pref/kernels/$kernel/kernel.json"

cat "$kernelpath" | python -c "import json; import sys; import os; \
f = open(os.environ['kernelpath'], 'w'); dic = json.loads(sys.stdin.read()); \
dic['argv'][0] = os.environ['wrap'].replace(chr(92), '/'); \
json.dump(dic, f); f.close()"
