#!/bin/bash
cd ~/miniconda3/bin

current_dir="$(pwd)"
export PATH="$PATH:${current_dir}"

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${script_dir}"

export PYTHONNOUSERSITE=1
conda env create --file ./env_unix.yaml

# do not specify custom -p/--prefix path
# this might make shortcut creation fail
