#!/bin/bash

# inverse order of channels:
conda config --env --add channels conda-forge
conda config --env --add channels defaults


pip install ./app-0.1.0.tar.gz || . "$exi"
app-ready
# python -m ipykernel install --user --name "$env"
